# cloudbuild.base.yaml
# このファイルは「土台イメージ」専用のビルド設定だよ！
steps:
- name: 'gcr.io/cloud-builders/docker'
  # `-f` オプションで、さっき作った `base.Dockerfile` を指定してビルドする！
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ep-x-backend-base:latest', '-f', 'base.Dockerfile', '.' ]

# ビルドしたイメージを登録
images:
- 'gcr.io/$PROJECT_ID/ep-x-backend-base:latest'

# 依存関係のインストールは時間がかかるから、性能高めのマシンと長めのタイムアウトを設定！
options:
  machineType: 'N1_HIGHCPU_8'
timeout: 3600s 